# Generated by Django 3.2.9 on 2021-11-15 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('state', models.PositiveSmallIntegerField(choices=[('0', 'Pendiente'), ('1', 'Aprobado'), ('3', 'Rechazado')], default=0, verbose_name='Estado')),
                ('checked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheked', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado/Rechazado por')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='destiny', to='store.store', verbose_name='Destino')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origin', to='store.store', verbose_name='Origen')),
                ('requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadoinventory_move_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadoinventory_move_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
    ]
