# Generated by Django 3.2.9 on 2021-11-15 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterField(
            model_name='move',
            name='checked',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cheked', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado/Rechazado por'),
        ),
        migrations.AlterField(
            model_name='move',
            name='requested',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requested', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AlterField(
            model_name='move',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobado'), (3, 'Rechazado')], default=0, verbose_name='Estado'),
        ),
    ]
