# Generated by Django 3.2.9 on 2021-11-15 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_auto_20211115_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='checked',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheked', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado/Rechazado por'),
        ),
    ]
