# Generated by Django 3.2.9 on 2021-11-15 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_alter_move_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='requested',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
    ]
