# Generated by Django 3.2.9 on 2021-11-15 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_detailproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_alter_move_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('lot', models.CharField(max_length=50, verbose_name='Lote')),
                ('subtotal', models.FloatField(verbose_name='Subtotal')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.move', verbose_name='Movimiento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadoinventory_detailmove_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadoinventory_detailmove_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento',
                'verbose_name_plural': 'Detalle de Movimientos',
            },
        ),
    ]
