# Generated by Django 3.2.9 on 2021-11-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211117_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio Compra'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio Compra'),
        ),
    ]
