# Generated by Django 3.2.9 on 2021-11-15 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20211115_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='userCreation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadoproduct_category_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:'),
        ),
        migrations.AlterField(
            model_name='category',
            name='userUpdate',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadoproduct_category_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='userCreation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadoproduct_product_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='userUpdate',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadoproduct_product_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:'),
        ),
    ]
