# Generated by Django 3.2.9 on 2021-11-15 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_auto_20211115_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('lot', models.PositiveIntegerField(null=True, verbose_name='Lote')),
                ('buy_price', models.FloatField(verbose_name='Precio de Compra')),
                ('sale_price', models.FloatField(verbose_name='Precio de Venta')),
                ('date_expiration', models.DateField(verbose_name='Fecha de Caducidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadoproduct_detailproduct_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadoproduct_detailproduct_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'DetailProduct',
                'verbose_name_plural': 'DetailProducts',
            },
        ),
    ]
