# Generated by Django 3.2.9 on 2021-11-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211118_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio Venta'),
        ),
    ]
