# Generated by Django 3.2.9 on 2021-11-17 17:20

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0006_remove_store_employe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('phone', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese solamente numeros', regex='^[0-9]*$'), core.models.val_tel], verbose_name='Telefono')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Gerente'), (1, 'Administrador'), (2, 'Vendedor')], default=0, verbose_name='Rol')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Tienda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadoemploye_employe_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadoemploye_employe_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
