# Generated by Django 3.2.9 on 2021-11-19 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:')),
                ('updateDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('initial_mount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='Monto de Apertura')),
                ('final_mount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='Monto de Apertura')),
                ('state', models.BooleanField(choices=[(True, 'Caja Abierta'), (False, 'Caja Cerrada')], default=True, help_text='Al crear la caja se apertura abierta por default', verbose_name='Estado de la Caja')),
                ('store', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Tienda')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadosale_salebox_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadosale_salebox_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:')),
                ('updateDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('client', models.CharField(max_length=75, verbose_name='Cliente')),
                ('nit', models.CharField(default='C/F', max_length=9, verbose_name='NIT')),
                ('address', models.CharField(default='Ciudad', max_length=75, verbose_name='Direccion')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadosale_sale_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadosale_sale_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetailSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:')),
                ('updateDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeinventory', verbose_name='Producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.sale', verbose_name='Venta')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadosale_detailsale_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadosale_detailsale_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
