# Generated by Django 3.2.9 on 2021-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20211118_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='address',
            field=models.CharField(default='Ciudad', max_length=75, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='nit',
            field=models.CharField(default='C/F', max_length=9, verbose_name='NIT'),
        ),
    ]
