# Generated by Django 3.2.9 on 2021-11-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_sale_sale_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_box',
            new_name='salebox',
        ),
    ]
