# Generated by Django 3.2.9 on 2021-11-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_entry_destiny'),
        ('sale', '0003_rename_sale_box_sale_salebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebox',
            name='store',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Tienda'),
            preserve_default=False,
        ),
    ]
