# Generated by Django 3.2.9 on 2021-11-19 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0026_rename_tranfer_detailtransfer_transfer'),
        ('sale', '0003_auto_20211118_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SaleBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:')),
                ('updateDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('initial_mount', models.DecimalField(decimal_places=2, editable=False, max_digits=8, verbose_name='Monto de Apertura')),
                ('final_mount', models.DecimalField(decimal_places=2, editable=False, max_digits=8, verbose_name='Monto de Apertura')),
                ('state', models.BooleanField(default=True, verbose_name='Estad')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadosale_salebox_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadosale_salebox_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
