# Generated by Django 3.2.9 on 2021-11-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_entry_destiny'),
        ('sale', '0004_alter_salebox_store'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salebox',
            unique_together={('store', 'createDate', 'state')},
        ),
    ]
