# Generated by Django 3.2.9 on 2021-11-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_salebox_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salebox',
            unique_together=set(),
        ),
    ]
