# Generated by Django 3.2.9 on 2021-11-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[('0', 'Gerente'), ('1', 'Administrador'), ('2', 'Vendedor')], default=2, null=True),
        ),
    ]
