# Generated by Django 3.2.9 on 2021-11-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20211115_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('0', 'Gerente'), ('1', 'Administrador'), ('2', 'Vendedor')], default=2, null=True, verbose_name='Rol'),
        ),
    ]
