# Generated by Django 3.2.9 on 2021-11-16 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('registration', '0005_auto_20211116_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cui',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CUI'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sotre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
