# Generated by Django 3.2.9 on 2021-11-16 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('registration', '0007_auto_20211116_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cui',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='store',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[('0', 'Gerente'), ('1', 'Administrador'), ('2', 'Vendedor')], default=2, null=True, verbose_name='Rol')),
                ('cui', models.CharField(blank=True, max_length=15, null=True, verbose_name='CUI')),
                ('phone', models.CharField(blank=True, max_length=8, null=True, verbose_name='Telefono')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Genero')),
                ('sotre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_id', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadoregistration_profile_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadoregistration_profile_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
