# Generated by Django 3.2.9 on 2021-11-17 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
                ('address', models.CharField(max_length=125, verbose_name='Direccion')),
                ('phone', models.CharField(max_length=8, verbose_name='Telefono')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadodepot_depot_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadodepot_depot_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
