# Generated by Django 3.2.9 on 2021-11-19 17:36

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:')),
                ('updateDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
                ('address', models.CharField(max_length=125, verbose_name='Direccion')),
                ('phone', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese solamente numeros', regex='^[0-9]*$'), core.models.val_tel], verbose_name='Telefono')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadostore_store_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadostore_store_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:')),
                ('updateDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('comentary', models.TextField(verbose_name='Comentario')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True, verbose_name='Total')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobado'), (2, 'Rechazado')], default=0, verbose_name='Estado')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny', to='store.store', verbose_name='Destino')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='store.store', verbose_name='Origen')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadostore_transfer_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadostore_transfer_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:')),
                ('updateDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('comentary', models.TextField(verbose_name='Comentario')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True, verbose_name='Total')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobado'), (2, 'Rechazado')], default=0, verbose_name='Estado')),
                ('destiny', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal', to='store.store', verbose_name='Destino')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadostore_entry_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadostore_entry_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetailTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:')),
                ('updateDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('expiration', models.DateField(blank=True, help_text='Indispensable para productos perecederos', null=True, verbose_name='Fecha de Expiracion')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.transfer', verbose_name='Transferencia')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadostore_detailtransfer_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadostore_detailtransfer_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Detalle Movimiento',
                'verbose_name_plural': 'Detalle Movimientos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetailEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:')),
                ('updateDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('expiration', models.DateField(blank=True, help_text='Indispensable para productos perecederos', null=True, verbose_name='Fecha de Expiracion')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.entry', verbose_name='Transferencia')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider', verbose_name='Proveedor')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadostore_detailentry_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadostore_detailentry_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Detalle Entrada',
                'verbose_name_plural': 'Detalle Entradas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:')),
                ('updateDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Tienda')),
                ('userCreation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadostore_storeinventory_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:')),
                ('userUpdate', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadostore_storeinventory_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:')),
            ],
            options={
                'verbose_name': 'Inventario en Tienda',
                'verbose_name_plural': 'Inventario en Tiendas',
                'db_table': '',
                'permissions': [('can_deliver_pizzas', 'Can deliver pizzas')],
                'managed': True,
                'unique_together': {('store', 'product')},
            },
        ),
    ]
