# Generated by Django 3.2.9 on 2021-11-17 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_alter_store_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinventory',
            name='createDate',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:'),
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='userCreation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadostore_storeinventory_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:'),
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='userUpdate',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadostore_storeinventory_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:'),
        ),
    ]
