# Generated by Django 3.2.9 on 2021-11-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211117_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinventory',
            name='stocks',
            field=models.PositiveIntegerField(default=0, verbose_name='Existencias'),
        ),
    ]
