# Generated by Django 3.2.9 on 2021-11-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211117_1637'),
        ('store', '0004_alter_storeinventory_stocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeinventory',
            options={'managed': True, 'permissions': [('can_deliver_pizzas', 'Can deliver pizzas')], 'verbose_name': 'Inventario en Tienda', 'verbose_name_plural': 'Inventario en Tiendas'},
        ),
        migrations.AlterField(
            model_name='storeinventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Tienda'),
        ),
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together={('store', 'product')},
        ),
    ]
