# Generated by Django 3.2.9 on 2021-11-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211117_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='employe',
        ),
    ]
