# Generated by Django 3.2.9 on 2021-11-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_trasnfer_detailtransfer_tranfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtransfer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeinventory', verbose_name='Producto'),
        ),
    ]
