# Generated by Django 3.2.9 on 2021-11-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_detailtransfer_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'managed': True, 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
    ]
