# Generated by Django 3.2.9 on 2021-11-17 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_alter_transfer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('expiration', models.DateField(blank=True, help_text='Indispensable para productos perecederos', null=True, verbose_name='Fecha de Expiracion')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeinventory', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle Entrada',
                'verbose_name_plural': 'Detalle Entradas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny', to='store.store', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='destiny',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='userCreation',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='userUpdate',
        ),
        migrations.DeleteModel(
            name='DetailTransfer',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.AddField(
            model_name='detailentry',
            name='tranfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.entry', verbose_name='Transferencia'),
        ),
        migrations.AddField(
            model_name='detailentry',
            name='userCreation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadostore_detailentry_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:'),
        ),
        migrations.AddField(
            model_name='detailentry',
            name='userUpdate',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadostore_detailentry_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:'),
        ),
    ]
