# Generated by Django 3.2.9 on 2021-11-17 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_tranfer_detailentry_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='subtotal',
            new_name='total',
        ),
    ]
