# Generated by Django 3.2.9 on 2021-11-17 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211117_1905'),
        ('store', '0014_rename_subtotal_transfer_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='detailtransfer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto'),
        ),
    ]
