# Generated by Django 3.2.9 on 2021-11-17 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_auto_20211117_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='comentary',
            field=models.TextField(default=1, verbose_name='Comentario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='createDate',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:'),
        ),
        migrations.AddField(
            model_name='entry',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Subtotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='userCreation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Creadostore_entry_related', to=settings.AUTH_USER_MODEL, verbose_name='Creado por:'),
        ),
        migrations.AddField(
            model_name='entry',
            name='userUpdate',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modificadostore_entry_related', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por:'),
        ),
    ]
