# Generated by Django 3.2.9 on 2021-11-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20211117_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Subtotal'),
        ),
    ]
