# Generated by Django 3.2.9 on 2021-11-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20211117_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True, verbose_name='Total'),
        ),
    ]
