# Generated by Django 3.2.9 on 2021-11-18 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20211118_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinventory',
            name='entry',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.entry'),
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='transfer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.transfer'),
        ),
    ]
