# Generated by Django 3.2.9 on 2021-11-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20211118_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailentry',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='detailtransfer',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal'),
        ),
    ]
