# Generated by Django 3.2.9 on 2021-11-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20211118_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailentry',
            name='updateDate',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:'),
        ),
        migrations.AddField(
            model_name='detailtransfer',
            name='updateDate',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:'),
        ),
        migrations.AddField(
            model_name='entry',
            name='updateDate',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:'),
        ),
        migrations.AddField(
            model_name='store',
            name='updateDate',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:'),
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='updateDate',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='updateDate',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha Modificacion:'),
        ),
        migrations.AlterField(
            model_name='detailentry',
            name='createDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:'),
        ),
        migrations.AlterField(
            model_name='detailtransfer',
            name='createDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='createDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:'),
        ),
        migrations.AlterField(
            model_name='store',
            name='createDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:'),
        ),
        migrations.AlterField(
            model_name='storeinventory',
            name='createDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='createDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Creacion:'),
        ),
    ]
