# Generated by Django 3.2.9 on 2021-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20211118_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobado'), (2, 'Rechazado')], default=0, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobado'), (2, 'Rechazado')], default=0, verbose_name='Estado'),
        ),
    ]
