# Generated by Django 3.2.9 on 2021-11-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_storeinventory_stocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailtransfer',
            old_name='tranfer',
            new_name='transfer',
        ),
    ]
